In [1]:
import pandas as pd
data={'Name':['Jagadesh','Ajay','Vicky','Koushal','Naveen','Tharun','Vishnu Varma','Ravi Varma'],'Science':[100,83,78,77,90,79,91,98],
      'Social':[67,89,56,87,89,76,74,89],'Maths':[56,87,76,45,86,68,75,67],'2lang':[98,88,66,44,47,23,56,98]}

df=pd.DataFrame(data)


In [2]:
print(df)

           Name  Science  Social  Maths  2lang
0      Jagadesh      100      67     56     98
1          Ajay       83      89     87     88
2         Vicky       78      56     76     66
3       Koushal       77      87     45     44
4        Naveen       90      89     86     47
5        Tharun       79      76     68     23
6  Vishnu Varma       91      74     75     56
7    Ravi Varma       98      89     67     98


In [3]:
df['Social'].mean()
#Average of all columns called as mean

np.float64(78.375)

In [5]:
df['Social'].mode()
#Mode shows the repating or common value which is present in the data set

0    89
Name: Social, dtype: int64

In [7]:
df['Social'].median()
#it shows the midle value in the data set

np.float64(81.5)

#Scalars and vectors

In [ ]:
#Scalars are the individual entities in the data set example like x=9.7

In [8]:
#Vectors are the colection of numbers which can be represented using list and arrays
import numpy as np
df1=np.array([12,43,667,78,-90])
df1


array([ 12,  43, 667,  78, -90])

In [10]:
#Matrics are the two dimensional arrays array of numeric numbers
mat=np.array([[12,45,67],[23,76,45],[80,78,34]])
mat

array([[12, 45, 67],
       [23, 76, 45],
       [80, 78, 34]])

In [12]:
#Slicing in python
 

In [20]:
#Slicing the Matrix to print  row
mat[:1]

array([[12, 45, 67]])

In [18]:
#Printing the array from the second row to third row
mat[1:3]

array([[23, 76, 45],
       [80, 78, 34]])

In [21]:
mat[1:]

array([[23, 76, 45],
       [80, 78, 34]])

In [22]:
mat[2:3]

array([[80, 78, 34]])

In [26]:
#printing single element using slicing where 2:3 represent 3rd row and  1:2 represent 2 column
mat[2:3,1:2]
 

array([[78]])

Linear Combination

In [30]:
'''Linear combination is combination of vectors by multiplying the data with scalar vectors v1 and v2​, 
and scalars a and b, the expression a × v1 + b × v2'''
#let us consider scaler a=10 b=5 and vector x=[[6,7],[6,5]] y=[[3,4],[6,8]]
#let us compute for a*x
a=10
x=np.array([[6,7],[6,5]])
b=5
y=np.array([[3,4],[6,8]])
c=a*x
d=b*y
linearcombination=c+d
print(linearcombination)

 

[[75 90]
 [90 90]]


In [33]:
'''Eigen  vector are the non singular identity eigen values are singular identity
 The vector that only changes by a scalar factor after applying a transformation is called an eigenvector
 the scalar value attached to the eigenvector is called the eigenvalue.'''
p=np.array([[3,4,5],[4,6,7],[7,8,9]])
m=np.linalg.eig(p)
print(m)

EigResult(eigenvalues=array([18.42246644, -0.72284407,  0.30037763]), eigenvectors=array([[-0.38311553, -0.45878386,  0.36722111],
       [-0.5440145 , -0.49520469, -0.81289768],
       [-0.74650567,  0.73775991,  0.45204648]]))


In [37]:
#scalar dot product means it taakes two vectors with same dimension to give scaler value
k=np.array([[4,6],[8,10]])
p=np.array([[7,8],[6,23]])
o=np.dot(k,p)
print(o)

[[ 64 170]
 [116 294]]


In [36]:
#Vector dot product take tw# Define two matrices (2D arrays)
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

# Calculate the dot product (matrix multiplication)
result_matrix = np.dot(A, B)

print(result_matrix)


[[ 58  64]
 [139 154]]


In [44]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8,9],
              [9, 10,8]])
#cross product of two array of first row
crossmat=np.linalg.cross(A[0],B[0])
#transpose of matrix
transpos=np.transpose(A)
#singular value decomposition
svd=np.linalg.svd(A)
#finding rank of a matrix
rankofmat=np.linalg.matrix_rank(A)

 

np.int64(2)

Cosine Similarity


In [53]:
#Cosine similarity is the mthod to find the similarity between two vectors
#1.Euclidan distance
import numpy as np
p = np.array([1, 2])
q = np.array([4, 6])
eucl=np.linalg.norm(p-q)
print("Euclidan distance",eucl)
#2.Manhattan
manh=np.sum(abs(p-q))
print("Manhattan",manh)
#3.Jaccard Similarity
A = {1, 2, 3, 4}
B = {3, 4, 5, 6}
jaccard_similarity = len(A.intersection(B)) / len(A.union(B))
print("Jaccard Similarity:", jaccard_similarity)
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# 4. Cosine similarity
cosine_similarity = np.dot(A, B) / (np.linalg.norm(A) * np.linalg.norm(B))
print("Cosine Similarity:", cosine_similarity)

Euclidan distance 5.0
Manhattan 7
Jaccard Similarity: 0.3333333333333333
Cosine Similarity: 0.9746318461970762


Probability and statistics

In [ ]:
''' Probability is all about chance. Whereas statistics is more about
how we handle various data using different techniques.'''


In [ ]:
'''Sample Space Probability is a fundamental concept in probability theory 
that refers to the set of all possible outcomes of a random experiment. 
The sample space is denoted by the symbol ( S ) 
and can be finite or infinite, depending on the nature of the experiment.
Finite Sample Space: Contains a finite number of outcomes.

Example: Rolling a die, flipping a coin, drawing a card from a deck.
Infinite Sample Space: Contains an infinite number of outcomes.

Example: The set of all possible outcomes when measuring the height of individuals (which can take any value within a range).'''



In [54]:
sample_space = np.array([1, 2, 3, 4, 5, 6])

# Define the event of rolling an even number
event = np.array([2, 4, 6])

# Calculate the probability of the event
total_outcomes = len(sample_space)
favorable_outcomes = len(event)

# Probability of rolling an even number
probability_even = favorable_outcomes / total_outcomes

print("Sample Space:", sample_space)
print("Event (Even Numbers):", event)
print("Probability of rolling an even number:", probability_even)

Sample Space: [1 2 3 4 5 6]
Event (Even Numbers): [2 4 6]
Probability of rolling an even number: 0.5


In [ ]:
'''Probability means the likely event that ocurs on the total events'''
